include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - test/**
  errors:
    must_be_immutable: error
    one_member_abstracts: ignore
    only_throw_errors: ignore
    use_key_in_widget_constructors: error
linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
